#!/usr/bin/env bash

if emacsclient -e t > /dev/null 2>&1; then
  # Server is running
  if [[ -n "$INSIDE_EMACS" ]]; then
    # Inside Emacs
    exit 10 # Test code
  else
    # Not inside Emacs
    exit 11 # Test code
  fi
else
  # Server is not running
  exit 1
fi
