#!/usr/bin/env bash

if emacsclient -e t > /dev/null 2>&1; then
  # Server is running
  if [[ -n "$INSIDE_EMACS" ]]; then
    # Inside Emacs
    emacsclient "$@"
  else
    # Not inside Emacs
    emacsclient -nw "$@"
  fi
else
  # Server is not running
  emacs -q "$@"
fi
