#Live config reload (changes require restart)
live_config_reload=true
[scrolling]
# Specifying '0' will disable scrolling.
history=100000
# Number of lines the viewport will move for every line scrolled when
# scrollback is enabled (history > 0).
multiplier= 3

[font]
normal={style="Regular", family = "Hack Nerd Font Mono"}
bold={style="Bold", family = "Hack Nerd Font Mono"}
italic={style="Italic", family = "Hack Nerd Font Mono"}
bold_italic={style="Bold Italic", family = "Hack Nerd Font Mono"}
size = @fontSize@

# Colors (Dracula)
# Default colors
[colors.primary]
background= '#282a36'
foreground= '#f8f8f2'

  # Normal colors
[colors.normal]
black=   '#000000'
red=     '#ff5555'
green=   '#50fa7b'
yellow=  '#f1fa8c'
blue=    '#bd93f9'
magenta= '#ff79c6'
cyan=    '#8be9fd'
white=   '#bbbbbb'

  # Bright colors
[colors.bright]
black=   '#555555'
red=     '#ff5555'
green=   '#50fa7b'
yellow=  '#f1fa8c'
blue=    '#caa9fa'
magenta= '#ff79c6'
cyan=    '#8be9fd'
white=   '#ffffff'

[selection]
# This string contains all characters that are used as separators for
# "semantic words" in Alacritty.
semantic_escape_chars= ",│`|:\"' ()[]{}<>\t"
# When set to `true`, selected text will be copied to the primary clipboard.
save_to_clipboard=true


[window]
# Allow terminal applications to change Alacritty’s window title.
dynamic_title=true

[cursor]
style="Block"
unfocused_hollow=true
